project='YUI'
title='YUI User Interface'
description='A Lua declarative GUI library'
format='markdown'
backtick_references=false
--file='../ldoc.lua'
dir='doc'
--readme='doc.md'
style='!pale'
--kind_names={topic='Manual',script='Programs'}
--[[examples = {
    '../tests/styles/colon.lua',
    '../tests/styles/four.lua',
    '../tests/styles/three.lua',
    '../tests/styles/multiple.lua',
    '../tests/example/mylib.c',
    '../tests/moonscript/List.moon',
}]]

